--[[
    Paragon Rework: custom glyph slot (milestone 225)

    A seventh, major-only glyph slot rendered in the center of the client's
    glyph flower. The 3.3.5 protocol caps real glyph slots at six, so this
    slot never touches the stock glyph fields: the applied glyph is recorded
    in acore_ale.paragon_custom_glyph and its passive aura is cast/reconciled
    by this module. The client half (Paragon_GlyphSlot.lua) draws the socket
    and sends apply requests over its own CSMH prefix.

    Wire protocol (prefix "ParagonGlyph"):
      client -> server [1]: { item = <glyph item id> }   apply request
      server -> client [1]: { aura = <spell id or 0>, error = <string?> }

    Glyph data (item -> property/aura/type/class) comes from
    paragon_glyph_data.lua, generated by Tools/gen_glyph_data.py.
]]

local MILESTONE_LEVEL = 350 -- track reorder 2026-08-18 (was 225)
local PREFIX = "ParagonGlyph"

-- PLAYER_FIELD_GLYPHS_1 (UpdateFields.h: UNIT_END 0x94 + 0x492) — the six
-- stock sockets' GlyphProperties ids, used for the duplicate check.
local GLYPH_FIELD_BASE = 1318
local STOCK_SLOTS = 6

CharDBExecute([[
CREATE TABLE IF NOT EXISTS acore_ale.paragon_custom_glyph (
    guid INT UNSIGNED NOT NULL PRIMARY KEY,
    item INT UNSIGNED NOT NULL,
    property INT UNSIGNED NOT NULL,
    aura INT UNSIGNED NOT NULL
) ENGINE=InnoDB;
]])

-- ============================================================================
-- RECORD CACHE (per-session; false = confirmed no record)
-- ============================================================================

local function LoadRecord(player)
    local cached = player:GetData("ParagonGlyphSlot")
    if cached ~= nil then
        return cached
    end
    local rec = false
    local q = CharDBQuery(string.format(
        "SELECT item, property, aura FROM acore_ale.paragon_custom_glyph WHERE guid = %d;",
        player:GetGUIDLow()))
    if q then
        rec = { item = q:GetUInt32(0), property = q:GetUInt32(1), aura = q:GetUInt32(2) }
    end
    player:SetData("ParagonGlyphSlot", rec)
    return rec
end

local function SaveRecord(player, rec)
    CharDBExecute(string.format(
        "REPLACE INTO acore_ale.paragon_custom_glyph (guid, item, property, aura) VALUES (%d, %d, %d, %d);",
        player:GetGUIDLow(), rec.item, rec.property, rec.aura))
    player:SetData("ParagonGlyphSlot", rec)
end

-- ============================================================================
-- AURA RECONCILE + CLIENT STATE
-- ============================================================================

local function Owed(player, paragon)
    -- account-wide paragon: benefits require character level 80
    return paragon and paragon:GetLevel() >= MILESTONE_LEVEL
        and player:GetLevel() >= 80
end

local function Reconcile(player, paragon)
    local rec = LoadRecord(player)
    if not rec then
        return
    end
    if Owed(player, paragon) then
        if not player:HasAura(rec.aura) then
            local aura = player:AddAura(rec.aura, player)
            if aura then
                aura:SetMaxDuration(-1)
                aura:SetDuration(-1)
            end
        end
    elseif player:HasAura(rec.aura) then
        player:RemoveAura(rec.aura)
    end
end

local function SendState(player, paragon, err)
    local rec = LoadRecord(player)
    local owed = rec and Owed(player, paragon)
    local def = owed and ParagonGlyphData[rec.item] or nil
    player:SendServerResponse(PREFIX, 1, {
        aura = owed and rec.aura or 0,
        rune = def and def.rune or nil,
        error = err,
    })
end

-- ============================================================================
-- APPLY REQUEST (client function 1)
-- ============================================================================

local function Fail(player, paragon, message)
    SendState(player, paragon, message)
    return false
end

function OnParagonGlyphApply(player, arg_table)
    local ok, err = pcall(function()
        if not player then
            return
        end
        local paragon = player:GetData("Paragon")
        local request = arg_table and arg_table[1]
        local item = request and tonumber(request.item)
        if not paragon or not item then
            return
        end

        if not Owed(player, paragon) then
            return Fail(player, paragon, "Requires Paragon level " .. MILESTONE_LEVEL .. ".")
        end

        local def = ParagonGlyphData[item]
        if not def then
            return Fail(player, paragon, "That item is not a glyph.")
        end
        if def.minor == 1 then
            return Fail(player, paragon, "Only major glyphs fit this slot.")
        end
        if def.class ~= player:GetClass() then
            return Fail(player, paragon, "That glyph is for another class.")
        end
        if not player:HasItem(item, 1) then
            return Fail(player, paragon, "You do not have that glyph.")
        end

        for i = 0, STOCK_SLOTS - 1 do
            if player:GetUInt32Value(GLYPH_FIELD_BASE + i) == def.property then
                return Fail(player, paragon, "That glyph is already active in one of your sockets.")
            end
        end
        local rec = LoadRecord(player)
        if rec and rec.property == def.property then
            return Fail(player, paragon, "That glyph is already in this slot.")
        end

        player:RemoveItem(item, 1)
        if rec and rec.aura ~= def.aura and player:HasAura(rec.aura) then
            player:RemoveAura(rec.aura)
        end
        SaveRecord(player, { item = item, property = def.property, aura = def.aura })
        Reconcile(player, paragon)
        SendState(player, paragon)
    end)
    if not ok then
        print("[Paragon] glyph slot apply error: " .. tostring(err))
    end
end

RegisterClientRequests({ Prefix = PREFIX, Functions = { [1] = "OnParagonGlyphApply" } })

-- ============================================================================
-- LIFECYCLE
-- ============================================================================

RegisterMediatorEvent("OnAfterUpdatePlayerStatistics", function(player, paragon, apply)
    local ok, err = pcall(function()
        if player and paragon and apply then
            Reconcile(player, paragon)
        end
    end)
    if not ok then
        print("[Paragon] glyph slot reconcile error: " .. tostring(err))
    end
end)

RegisterMediatorEvent("OnParagonLevelChanged", function(player, paragon)
    local ok, err = pcall(function()
        if player and paragon then
            Reconcile(player, paragon)
            SendState(player, paragon)
        end
    end)
    if not ok then
        print("[Paragon] glyph slot level-change error: " .. tostring(err))
    end
end)

RegisterMediatorEvent("OnAfterClientLoadRequest", function(player, paragon)
    local ok, err = pcall(function()
        if player and paragon then
            SendState(player, paragon)
        end
    end)
    if not ok then
        print("[Paragon] glyph slot state-push error: " .. tostring(err))
    end
end)

print("[Paragon] Rework: custom glyph slot module loaded")
