-- Generated by Tools/gen_glyph_data.py (do not hand-edit).
-- ParagonGlyphData[itemId] = { class=char class id, property=GlyphProperties id,
--                              aura=glyph passive spell, minor=1 for minor glyphs,
--                              rune=socket art the client shows when filled }
ParagonGlyphData = {
  [40896] = { class=11, property=161, aura=54810, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Frenzied Regeneration
  [40897] = { class=11, property=162, aura=54811, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Maul
  [40899] = { class=11, property=163, aura=54812, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Growl
  [40900] = { class=11, property=164, aura=54813, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Mangle
  [40901] = { class=11, property=165, aura=54815, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Shred
  [40902] = { class=11, property=166, aura=54818, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Rip
  [40903] = { class=11, property=167, aura=54821, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Rake
  [40906] = { class=11, property=168, aura=54824, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Swiftmend
  [40908] = { class=11, property=169, aura=54832, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Innervate
  [40909] = { class=11, property=170, aura=54733, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Rebirth
  [40912] = { class=11, property=171, aura=54743, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Regrowth
  [40913] = { class=11, property=172, aura=54754, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Rejuvenation
  [40914] = { class=11, property=173, aura=54825, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Healing Touch
  [40915] = { class=11, property=174, aura=54826, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Lifebloom
  [40916] = { class=11, property=175, aura=54845, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Starfire
  [40919] = { class=11, property=176, aura=54830, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Insect Swarm
  [40920] = { class=11, property=177, aura=54831, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Hurricane
  [40921] = { class=11, property=178, aura=54828, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Starfall
  [40922] = { class=11, property=179, aura=54756, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Wrath
  [40923] = { class=11, property=180, aura=54829, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Moonfire
  [40924] = { class=11, property=181, aura=54760, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Entangling Roots
  [41092] = { class=2, property=183, aura=54922, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Judgement
  [41094] = { class=2, property=184, aura=54925, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Seal of Command
  [41095] = { class=2, property=185, aura=54923, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Hammer of Justice
  [41096] = { class=2, property=186, aura=54924, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Spiritual Attunement
  [41097] = { class=2, property=187, aura=54926, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Hammer of Wrath
  [41098] = { class=2, property=188, aura=54927, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Crusader Strike
  [41099] = { class=2, property=189, aura=54928, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Consecration
  [41100] = { class=2, property=190, aura=54929, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Righteous Defense
  [41101] = { class=2, property=191, aura=54930, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Avenger's Shield
  [41102] = { class=2, property=192, aura=54931, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Turn Evil
  [41103] = { class=2, property=193, aura=54934, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Exorcism
  [41104] = { class=2, property=194, aura=54935, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Cleansing
  [41105] = { class=2, property=195, aura=54936, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Flash of Light
  [41106] = { class=2, property=196, aura=54937, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Holy Light
  [41107] = { class=2, property=197, aura=54938, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Avenging Wrath
  [41108] = { class=2, property=198, aura=54939, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Divinity
  [41109] = { class=2, property=199, aura=54940, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Seal of Wisdom
  [41110] = { class=2, property=200, aura=54943, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Seal of Light
  [41517] = { class=7, property=212, aura=55437, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Chain Heal
  [41518] = { class=7, property=213, aura=55449, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Chain Lightning
  [41524] = { class=7, property=214, aura=55454, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Lava
  [41526] = { class=7, property=215, aura=55442, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Shocking
  [41527] = { class=7, property=216, aura=55439, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Earthliving Weapon
  [41529] = { class=7, property=217, aura=55455, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Fire Elemental Totem
  [41530] = { class=7, property=218, aura=55450, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Fire Nova
  [41531] = { class=7, property=219, aura=55447, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Flame Shock
  [41532] = { class=7, property=220, aura=55451, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Flametongue Weapon
  [41533] = { class=7, property=222, aura=55456, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Healing Stream Totem
  [41534] = { class=7, property=223, aura=55440, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Healing Wave
  [41535] = { class=7, property=224, aura=55438, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Lesser Healing Wave
  [41536] = { class=7, property=226, aura=55453, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Lightning Bolt
  [41537] = { class=7, property=225, aura=55448, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Lightning Shield
  [41538] = { class=7, property=227, aura=55441, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Mana Tide Totem
  [41539] = { class=7, property=228, aura=55446, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Stormstrike
  [41540] = { class=7, property=229, aura=55444, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Lava Lash
  [41541] = { class=7, property=211, aura=55436, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Water Mastery
  [41542] = { class=7, property=231, aura=55445, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Windfury Weapon
  [41547] = { class=7, property=221, aura=55443, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Frost Shock
  [41552] = { class=7, property=230, aura=55452, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Elemental Mastery
  [42396] = { class=5, property=251, aura=55675, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Circle of Healing
  [42397] = { class=5, property=252, aura=55677, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Dispel Magic
  [42398] = { class=5, property=253, aura=55684, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Fade
  [42399] = { class=5, property=254, aura=55678, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Fear Ward
  [42400] = { class=5, property=255, aura=55679, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Flash Heal
  [42401] = { class=5, property=256, aura=55683, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Holy Nova
  [42402] = { class=5, property=257, aura=55686, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Inner Fire
  [42403] = { class=5, property=258, aura=55673, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Lightwell
  [42404] = { class=5, property=259, aura=55691, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Mass Dispel
  [42405] = { class=5, property=260, aura=55688, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Mind Control
  [42406] = { class=5, property=261, aura=55681, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Shadow Word: Pain
  [42407] = { class=5, property=262, aura=55689, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Shadow
  [42408] = { class=5, property=263, aura=55672, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Power Word: Shield
  [42409] = { class=5, property=264, aura=55680, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Prayer of Healing
  [42410] = { class=5, property=265, aura=55676, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Psychic Scream
  [42411] = { class=5, property=266, aura=55674, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Renew
  [42412] = { class=5, property=267, aura=55690, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Scourge Imprisonment
  [42414] = { class=5, property=268, aura=55682, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Shadow Word: Death
  [42415] = { class=5, property=269, aura=55687, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Mind Flay
  [42416] = { class=5, property=270, aura=55692, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Smite
  [42417] = { class=5, property=271, aura=55685, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Spirit of Redemption
  [42453] = { class=9, property=272, aura=56242, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Incinerate
  [42454] = { class=9, property=273, aura=56235, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Conflagrate
  [42455] = { class=9, property=274, aura=56218, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Corruption
  [42456] = { class=9, property=275, aura=56241, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Curse of Agony
  [42457] = { class=9, property=276, aura=56232, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Death Coil
  [42458] = { class=9, property=277, aura=56244, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Fear
  [42459] = { class=9, property=278, aura=56246, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Felguard
  [42460] = { class=9, property=279, aura=56249, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Felhunter
  [42461] = { class=9, property=280, aura=56238, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Health Funnel
  [42462] = { class=9, property=281, aura=56224, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Healthstone
  [42463] = { class=9, property=282, aura=56217, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Howl of Terror
  [42464] = { class=9, property=283, aura=56228, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Immolate
  [42465] = { class=9, property=284, aura=56248, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Imp
  [42466] = { class=9, property=285, aura=56226, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Searing Pain
  [42467] = { class=9, property=286, aura=56240, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Shadow Bolt
  [42468] = { class=9, property=287, aura=56229, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Shadowburn
  [42469] = { class=9, property=288, aura=56216, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Siphon Life
  [42470] = { class=9, property=289, aura=56231, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Soulstone
  [42471] = { class=9, property=290, aura=56250, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Succubus
  [42472] = { class=9, property=291, aura=56233, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Unstable Affliction
  [42473] = { class=9, property=292, aura=56247, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Voidwalker
  [42734] = { class=8, property=311, aura=56360, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Arcane Explosion
  [42735] = { class=8, property=312, aura=56363, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Arcane Missiles
  [42736] = { class=8, property=313, aura=56381, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Arcane Power
  [42737] = { class=8, property=314, aura=56365, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Blink
  [42738] = { class=8, property=315, aura=56380, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Evocation
  [42739] = { class=8, property=316, aura=56368, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Fireball
  [42740] = { class=8, property=317, aura=56369, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Fire Blast
  [42741] = { class=8, property=318, aura=56376, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Frost Nova
  [42742] = { class=8, property=319, aura=56370, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Frostbolt
  [42743] = { class=8, property=320, aura=56384, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Ice Armor
  [42744] = { class=8, property=321, aura=56372, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Ice Block
  [42745] = { class=8, property=322, aura=56377, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Ice Lance
  [42746] = { class=8, property=323, aura=56374, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Icy Veins
  [42747] = { class=8, property=324, aura=56371, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Scorch
  [42748] = { class=8, property=325, aura=56366, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Invisibility
  [42749] = { class=8, property=326, aura=56383, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Mage Armor
  [42750] = { class=8, property=327, aura=56367, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Mana Gem
  [42751] = { class=8, property=328, aura=56382, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Molten Armor
  [42752] = { class=8, property=329, aura=56375, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Polymorph
  [42753] = { class=8, property=330, aura=56364, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Remove Curse
  [42754] = { class=8, property=331, aura=56373, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Water Elemental
  [42897] = { class=3, property=351, aura=56824, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Aimed Shot
  [42898] = { class=3, property=352, aura=56841, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Arcane Shot
  [42899] = { class=3, property=353, aura=56857, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of the Beast
  [42900] = { class=3, property=354, aura=56833, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Mending
  [42901] = { class=3, property=355, aura=56851, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Aspect of the Viper
  [42902] = { class=3, property=356, aura=56830, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Bestial Wrath
  [42903] = { class=3, property=357, aura=56850, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Deterrence
  [42904] = { class=3, property=358, aura=56844, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Disengage
  [42905] = { class=3, property=359, aura=56845, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Freezing Trap
  [42906] = { class=3, property=360, aura=56847, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Frost Trap
  [42907] = { class=3, property=361, aura=56829, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Hunter's Mark
  [42908] = { class=3, property=362, aura=56846, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Immolation Trap
  [42909] = { class=3, property=363, aura=56856, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of the Hawk
  [42910] = { class=3, property=364, aura=56836, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Multi-Shot
  [42911] = { class=3, property=365, aura=56828, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Rapid Fire
  [42912] = { class=3, property=366, aura=56832, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Serpent Sting
  [42913] = { class=3, property=367, aura=56849, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Snake Trap
  [42914] = { class=3, property=368, aura=56826, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Steady Shot
  [42915] = { class=3, property=369, aura=56842, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Trueshot Aura
  [42916] = { class=3, property=370, aura=56838, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Volley
  [42917] = { class=3, property=371, aura=56848, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Wyvern Sting
  [42954] = { class=4, property=391, aura=56808, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Adrenaline Rush
  [42955] = { class=4, property=392, aura=56813, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Ambush
  [42956] = { class=4, property=393, aura=56800, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Backstab
  [42957] = { class=4, property=394, aura=56818, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Blade Flurry
  [42958] = { class=4, property=395, aura=56820, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Crippling Poison
  [42959] = { class=4, property=396, aura=56806, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Deadly Throw
  [42960] = { class=4, property=397, aura=56799, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Evasion
  [42961] = { class=4, property=398, aura=56802, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Eviscerate
  [42962] = { class=4, property=399, aura=56803, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Expose Armor
  [42963] = { class=4, property=400, aura=56804, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Feint
  [42964] = { class=4, property=401, aura=56812, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Garrote
  [42965] = { class=4, property=402, aura=56814, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Ghostly Strike
  [42966] = { class=4, property=403, aura=56809, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Gouge
  [42967] = { class=4, property=404, aura=56807, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Hemorrhage
  [42968] = { class=4, property=405, aura=56819, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Preparation
  [42969] = { class=4, property=406, aura=56801, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Rupture
  [42970] = { class=4, property=407, aura=56798, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Sap
  [42971] = { class=4, property=408, aura=56805, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Vigor
  [42972] = { class=4, property=409, aura=56821, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Sinister Strike
  [42973] = { class=4, property=410, aura=56810, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Slice and Dice
  [42974] = { class=4, property=411, aura=56811, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Sprint
  [43316] = { class=11, property=431, aura=57856, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Aquatic Form
  [43331] = { class=11, property=434, aura=57857, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Unburdened Rebirth
  [43332] = { class=11, property=435, aura=57862, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Thorns
  [43334] = { class=11, property=432, aura=57858, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Challenging Roar
  [43335] = { class=11, property=433, aura=57855, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of the Wild
  [43338] = { class=3, property=439, aura=57866, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Revive Pet
  [43339] = { class=8, property=445, aura=57924, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Arcane Intellect
  [43340] = { class=2, property=453, aura=57958, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Blessing of Might
  [43342] = { class=5, property=458, aura=57985, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Fading
  [43343] = { class=4, property=466, aura=58017, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Pick Pocket
  [43344] = { class=7, property=474, aura=58055, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Water Breathing
  [43350] = { class=3, property=440, aura=57870, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Mend Pet
  [43351] = { class=3, property=441, aura=57903, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Feign Death
  [43354] = { class=3, property=444, aura=57900, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Possessed Strength
  [43355] = { class=3, property=443, aura=57904, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of the Pack
  [43356] = { class=3, property=442, aura=57902, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Scare Beast
  [43357] = { class=8, property=446, aura=57926, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Fire Ward
  [43359] = { class=8, property=448, aura=57928, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Frost Armor
  [43360] = { class=8, property=447, aura=57927, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Frost Ward
  [43361] = { class=8, property=450, aura=52648, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of the Penguin
  [43362] = { class=8, property=449, aura=58136, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of the Bear Cub
  [43364] = { class=8, property=451, aura=57925, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Slow Fall
  [43365] = { class=2, property=452, aura=57937, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Blessing of Kings
  [43366] = { class=2, property=454, aura=57979, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Blessing of Wisdom
  [43367] = { class=2, property=455, aura=57955, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Lay on Hands
  [43368] = { class=2, property=456, aura=57947, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Sense Undead
  [43369] = { class=2, property=457, aura=57954, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of the Wise
  [43370] = { class=5, property=459, aura=57987, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Levitate
  [43371] = { class=5, property=460, aura=58009, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Fortitude
  [43372] = { class=5, property=462, aura=58015, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Shadow Protection
  [43373] = { class=5, property=461, aura=57986, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Shackle Undead
  [43374] = { class=5, property=463, aura=58228, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Shadowfiend
  [43376] = { class=4, property=464, aura=58032, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Distract
  [43377] = { class=4, property=465, aura=58027, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Pick Lock
  [43378] = { class=4, property=467, aura=58033, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Safe Fall
  [43379] = { class=4, property=468, aura=58039, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Blurred Speed
  [43380] = { class=4, property=469, aura=58038, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Vanish
  [43381] = { class=7, property=470, aura=58058, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Astral Recall
  [43385] = { class=7, property=473, aura=58059, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Renewed Life
  [43386] = { class=7, property=475, aura=58063, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Water Shield
  [43388] = { class=7, property=476, aura=58057, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Water Walking
  [43389] = { class=9, property=477, aura=58079, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Unending Breath
  [43390] = { class=9, property=478, aura=58070, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Drain Soul
  [43391] = { class=9, property=479, aura=58081, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Kilrogg
  [43392] = { class=9, property=480, aura=58080, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Curse of Exhaustion
  [43393] = { class=9, property=481, aura=58107, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Enslave Demon
  [43394] = { class=9, property=482, aura=58094, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Souls
  [43395] = { class=1, property=483, aura=58095, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Battle
  [43396] = { class=1, property=484, aura=58096, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Bloodrage
  [43397] = { class=1, property=485, aura=58097, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Charge
  [43398] = { class=1, property=486, aura=58099, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Mocking Blow
  [43399] = { class=1, property=487, aura=58098, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Thunder Clap
  [43400] = { class=1, property=488, aura=58104, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Enduring Victory
  [43412] = { class=1, property=490, aura=58369, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Bloodthirst
  [43413] = { class=1, property=491, aura=58355, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Rapid Charge
  [43414] = { class=1, property=492, aura=58366, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Cleaving
  [43415] = { class=1, property=493, aura=58388, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Devastate
  [43416] = { class=1, property=494, aura=58367, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Execution
  [43417] = { class=1, property=495, aura=58372, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Hamstring
  [43418] = { class=1, property=496, aura=58357, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Heroic Strike
  [43419] = { class=1, property=497, aura=58377, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Intervene
  [43420] = { class=1, property=498, aura=58365, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Barbaric Insults
  [43421] = { class=1, property=489, aura=58368, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Mortal Strike
  [43422] = { class=1, property=499, aura=58386, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Overpower
  [43423] = { class=1, property=500, aura=58385, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Rending
  [43424] = { class=1, property=501, aura=58364, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Revenge
  [43425] = { class=1, property=502, aura=58375, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Blocking
  [43426] = { class=1, property=503, aura=58376, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Last Stand
  [43427] = { class=1, property=504, aura=58387, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Sunder Armor
  [43428] = { class=1, property=505, aura=58384, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Sweeping Strikes
  [43429] = { class=1, property=506, aura=58353, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Taunt
  [43430] = { class=1, property=507, aura=58356, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Resonating Power
  [43431] = { class=1, property=508, aura=58382, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Victory Rush
  [43432] = { class=1, property=509, aura=58370, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Whirlwind
  [43533] = { class=6, property=512, aura=58623, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Anti-Magic Shell
  [43534] = { class=6, property=513, aura=58616, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Heart Strike
  [43535] = { class=6, property=514, aura=58640, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Blood Tap
  [43536] = { class=6, property=515, aura=58673, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Bone Shield
  [43537] = { class=6, property=516, aura=58620, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Chains of Ice
  [43538] = { class=6, property=511, aura=58613, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Dark Command
  [43539] = { class=6, property=518, aura=58677, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Death's Embrace
  [43541] = { class=6, property=519, aura=62259, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Death Grip
  [43542] = { class=6, property=520, aura=58629, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Death and Decay
  [43543] = { class=6, property=521, aura=58647, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Frost Strike
  [43544] = { class=6, property=522, aura=58680, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Horn of Winter
  [43545] = { class=6, property=523, aura=58625, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Icebound Fortitude
  [43546] = { class=6, property=524, aura=58631, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Icy Touch
  [43547] = { class=6, property=525, aura=58671, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Obliterate
  [43548] = { class=6, property=526, aura=58657, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Plague Strike
  [43549] = { class=6, property=527, aura=58686, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of the Ghoul
  [43550] = { class=6, property=528, aura=58669, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Rune Strike
  [43551] = { class=6, property=529, aura=58642, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Scourge Strike
  [43552] = { class=6, property=530, aura=58618, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Strangulate
  [43553] = { class=6, property=531, aura=58635, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Unbreakable Armor
  [43554] = { class=6, property=532, aura=58676, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Vampiric Blood
  [43671] = { class=6, property=554, aura=59307, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Corpse Explosion
  [43672] = { class=6, property=553, aura=59309, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Pestilence
  [43673] = { class=6, property=555, aura=60200, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Raise Dead
  [43674] = { class=11, property=551, aura=59219, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Dash
  [43725] = { class=7, property=552, aura=59289, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Ghost Wolf
  [43825] = { class=6, property=556, aura=59327, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Rune Tap
  [43826] = { class=6, property=557, aura=59332, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Blood Strike
  [43827] = { class=6, property=558, aura=59336, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Death Strike
  [43867] = { class=2, property=559, aura=56420, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Holy Wrath
  [43868] = { class=2, property=560, aura=56414, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Seal of Righteousness
  [43869] = { class=2, property=561, aura=56416, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Seal of Vengeance
  [44432] = { class=6, property=527, aura=58686, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Raise Dead
  [44684] = { class=8, property=591, aura=61205, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Frostfire
  [44920] = { class=8, property=611, aura=62126, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Blast Wave
  [44922] = { class=11, property=613, aura=62135, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Typhoon
  [44923] = { class=7, property=612, aura=62132, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Thunderstorm
  [44928] = { class=11, property=631, aura=62080, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Focus
  [44955] = { class=8, property=651, aura=62210, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Arcane Blast
  [45601] = { class=11, property=671, aura=62969, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Berserk
  [45602] = { class=11, property=672, aura=62970, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Wild Growth
  [45603] = { class=11, property=673, aura=62971, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Nourish
  [45604] = { class=11, property=674, aura=63055, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Savage Roar
  [45622] = { class=11, property=675, aura=63056, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Monsoon
  [45623] = { class=11, property=676, aura=63057, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Barkskin
  [45625] = { class=3, property=677, aura=63065, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Chimera Shot
  [45731] = { class=3, property=691, aura=63066, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Explosive Shot
  [45732] = { class=3, property=692, aura=63067, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Kill Shot
  [45733] = { class=3, property=693, aura=63068, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Explosive Trap
  [45734] = { class=3, property=694, aura=63069, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Scatter Shot
  [45735] = { class=3, property=695, aura=63086, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Raptor Strike
  [45736] = { class=8, property=696, aura=63090, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Deep Freeze
  [45737] = { class=8, property=697, aura=63091, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Living Bomb
  [45738] = { class=8, property=698, aura=63092, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Arcane Barrage
  [45739] = { class=8, property=699, aura=63093, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Mirror Image
  [45740] = { class=8, property=700, aura=63095, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Ice Barrier
  [45741] = { class=2, property=701, aura=63218, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Beacon of Light
  [45742] = { class=2, property=702, aura=63219, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Hammer of the Righteous
  [45743] = { class=2, property=703, aura=63220, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Divine Storm
  [45744] = { class=2, property=704, aura=63222, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Shield of Righteousness
  [45745] = { class=2, property=705, aura=63223, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Divine Plea
  [45746] = { class=2, property=706, aura=63224, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Holy Shock
  [45747] = { class=2, property=707, aura=63225, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Salvation
  [45753] = { class=5, property=708, aura=63229, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Dispersion
  [45755] = { class=5, property=709, aura=63231, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Guardian Spirit
  [45756] = { class=5, property=710, aura=63235, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Penance
  [45757] = { class=5, property=711, aura=63237, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Mind Sear
  [45758] = { class=5, property=712, aura=63246, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Hymn of Hope
  [45760] = { class=5, property=713, aura=63248, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Pain Suppression
  [45761] = { class=4, property=714, aura=63249, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Hunger for Blood
  [45762] = { class=4, property=715, aura=63252, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Killing Spree
  [45764] = { class=4, property=716, aura=63253, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Shadow Dance
  [45766] = { class=4, property=731, aura=63254, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Fan of Knives
  [45767] = { class=4, property=732, aura=63256, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Tricks of the Trade
  [45768] = { class=4, property=733, aura=63268, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Mutilate
  [45769] = { class=4, property=734, aura=63269, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Cloak of Shadows
  [45770] = { class=7, property=735, aura=63270, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Thunder
  [45771] = { class=7, property=736, aura=63271, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Feral Spirit
  [45772] = { class=7, property=737, aura=63273, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Riptide
  [45775] = { class=7, property=751, aura=63279, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Earth Shield
  [45776] = { class=7, property=752, aura=63280, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Totem of Wrath
  [45777] = { class=7, property=753, aura=63291, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-1" }, -- Glyph of Hex
  [45778] = { class=7, property=754, aura=63298, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Stoneclaw Totem
  [45779] = { class=9, property=755, aura=63302, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-11" }, -- Glyph of Haunt
  [45780] = { class=9, property=756, aura=63303, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-12" }, -- Glyph of Metamorphosis
  [45781] = { class=9, property=757, aura=63304, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-13" }, -- Glyph of Chaos Bolt
  [45782] = { class=9, property=758, aura=63309, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-14" }, -- Glyph of Demonic Circle
  [45783] = { class=9, property=759, aura=63310, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-15" }, -- Glyph of Shadowflame
  [45785] = { class=9, property=760, aura=63320, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Life Tap
  [45789] = { class=9, property=761, aura=63312, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Soul Link
  [45790] = { class=1, property=762, aura=63324, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Bladestorm
  [45792] = { class=1, property=763, aura=63325, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-19" }, -- Glyph of Shockwave
  [45793] = { class=1, property=764, aura=63326, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Vigilance
  [45794] = { class=1, property=765, aura=63327, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-20" }, -- Glyph of Enraged Regeneration
  [45795] = { class=1, property=766, aura=63328, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-3" }, -- Glyph of Spell Reflection
  [45797] = { class=1, property=767, aura=63329, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-4" }, -- Glyph of Shield Wall
  [45799] = { class=6, property=768, aura=63330, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-5" }, -- Glyph of Dancing Rune Weapon
  [45800] = { class=6, property=769, aura=63331, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-6" }, -- Glyph of Hungering Cold
  [45803] = { class=6, property=770, aura=63332, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-7" }, -- Glyph of Unholy Blight
  [45804] = { class=6, property=771, aura=63333, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-8" }, -- Glyph of Dark Death
  [45805] = { class=6, property=772, aura=63334, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Disease
  [45806] = { class=6, property=773, aura=63335, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Howling Blast
  [45908] = { class=4, property=791, aura=64199, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune1" }, -- Glyph of Envenom
  [46372] = { class=11, property=811, aura=65243, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-16" }, -- Glyph of Survival Instincts
  [48720] = { class=11, property=831, aura=67598, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-2" }, -- Glyph of Claw
  [49084] = { class=1, property=851, aura=68164, minor=1, rune="Interface/Spellbook/UI-Glyph-Rune-17" }, -- Glyph of Command
  [50045] = { class=8, property=871, aura=70937, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-18" }, -- Glyph of Eternal Water
  [50077] = { class=9, property=911, aura=70947, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-9" }, -- Glyph of Quick Decay
  [50125] = { class=11, property=891, aura=71013, minor=0, rune="Interface/Spellbook/UI-Glyph-Rune-10" }, -- Glyph of Rapid Rejuvenation
}
