--[[
    Paragon Rework: solo dungeon clears (milestone 1200, universal)

    Every unique 5-man dungeon the character clears SOLO grants +2
    resilience rating and +0.25% critical strike damage (applied in whole
    percents: every 4 clears = +1%, by design — aura 163 amounts are
    integer percent). Each dungeon counts once, the first time its final
    encounter completes with the character alone in the instance; heroic
    versions are separate dungeons. 92 dungeons total.

    Detection: the §1p ALE hook MAP_EVENT_ON_ENCOUNTER_COMPLETE (server
    event 36) mirrors GlobalScript::OnAfterUpdateEncounterState — the
    core's own completion matcher in Map::UpdateEncounterState. It fires
    for BOTH credit types (boss kill and scripted spell credit: Culling of
    Stratholme, Drak'Tharon, Trial of the Champion, Halls of Reflection)
    with dungeonId = instance_encounters.lastEncounterDungeon, non-zero
    exactly when the FINAL encounter of (map, difficulty) was credited.
    No boss AI is replaced (RegisterCreatureEvent would hijack scripted
    AIs) and no InstanceScript is displaced.

    Solo check: map:GetPlayers() at credit time must contain exactly one
    player. Playerbots are real Player objects in the map's player list,
    so a bot inside the instance breaks solo — being in a group with
    players OUTSIDE the instance does not (nobody helped). Dungeon maps
    are per-instance objects, so the list is this run only.

    The DUNGEONS table is the allowlist (raids, UBRS and holiday bosses
    have final encounters too — absent ids never record) AND the display
    name source: the DB cannot map LFG dungeon ids to names (lfgdungeons_dbc
    is an empty override table), so the 92 ids are enumerated here from
    the instance_encounters census.

    Clears are recorded for any human character from module install on
    (no retroactivity — past clears carry no solo/group record); the
    milestone gates the STATS, not the registry, so progress made before
    reaching 1200 counts once the milestone unlocks.

    Accepted windows (all mirror core LFG-completion semantics):
      - a solo player who dies and RELEASES before the credit lands is
        outside the map at count time — that run records nothing (the run
        is repeatable after an instance reset);
      - Halls of Reflection credits ~19s into the escape outro (72830 is
        cast by the escort at UpdateOutro step 5) — leaving during the
        outro forfeits that run;
      - kill-credit finals follow core loot eligibility: the player (or
        their pets) must deal >= 50% of the boss's max health or the core
        never reaches KillRewarder (scripted allies soloing the boss for
        you records nothing).

    Crit damage carrier: server-only spell 1900118 (aura 163
    SPELL_AURA_MOD_CRIT_DAMAGE_BONUS, misc 127 = all schools) affects
    melee white crits, melee/ranged special + Auto Shot crits and all
    spell crits — not healing crits, mirroring the stock Chaotic Skyflare
    meta. bp passes through CastCustomSpell exactly (die 0); recast with a
    new bp rewrites the live aura. Same reconcile-owning-carrier rules as
    the gem-double mp5 aura: own spell id, ReconcileCrit runs on every
    eligible reconcile (the aura is death-persistent — a stale copy must
    be cleared at relog when nothing is owed).

    Tooltip: prefix "ParagonSolo" fn 1 pushes { count, total, resil,
    crit, next_at }; Paragon_RewardTrack.lua renders the live numbers
    under the milestone-1200 track node.

    Achievements (96, own "Solo Clears" subtab under Dungeons & Raids):
    one per dungeon (id 19000 + LFG dungeon id), three era metas
    (19301-03) and the "Pinnacle" capstone (19304, grants the Pinnacle
    title via achievement_reward). Rows are generated by
    Tools/paragon_client_patch.py into the client MPQ AND the
    acore_world achievement*_dbc override tables. The metas/capstone
    complete natively through type-8 COMPLETE_ACHIEVEMENT criteria
    chains; ReconcileAchievements below grants per-dungeon rows and
    doubles as the retro-grant for clears banked before the rows
    existed. Grants are unrelated to the milestone — the registry earns
    them, so achievements accrue below paragon 1200.
]]

local Constant = require("paragon_constant")

local PREFIX = "ParagonSolo"
local MILESTONE = 1200
local CRIT_SPELL = 1900118
local ENCOUNTER_EVENT = 36 -- §1p MAP_EVENT_ON_ENCOUNTER_COMPLETE
local RESIL_PER_CLEAR = 2
local CLEARS_PER_CRIT = 4 -- 4 x 0.25% = 1% (integer aura granularity)
local TOTAL = 92

local APPLIED_KEY = "ParagonSoloApplied"
local CRIT_KEY = "ParagonSoloCrit"
local PUSHED_KEY = "ParagonSoloPushed"
local CLEARS_KEY = "ParagonSoloClears"

-- In-game achievements (client rows + serverside achievement_dbc rows come
-- from Tools/paragon_client_patch.py — keep ids in sync with its
-- SOLO_ACH_* constants). Per-dungeon achievement id = ACH_BASE + dungeon
-- id; era metas and the capstone complete NATIVELY through type-8
-- (COMPLETE_ACHIEVEMENT) criteria chains, the SetAchievement calls below
-- are the primary grant for dungeons and an idempotent safety net for the
-- rest (Player::CompletedAchievement is HasAchieved-guarded). The capstone
-- carries the Pinnacle title via achievement_reward.
local ACH_BASE = 19000
local ACH_META = { classic = 19301, tbc = 19302, wotlk = 19303 }
local ACH_CAPSTONE = 19304
local ERA = {
    classic = { 1, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
                32, 34, 36, 38, 40, 163, 164, 165, 272, 273, 274, 276 },
    tbc     = { 136, 137, 138, 140, 146, 147, 148, 149, 150, 151, 170, 171,
                172, 173, 174, 198, 178, 179, 180, 181, 182, 183, 184, 185,
                186, 187, 188, 189, 190, 191, 192, 201 },
    wotlk   = { 202, 203, 204, 206, 207, 208, 209, 214, 216, 218, 220, 225,
                245, 251, 253, 255, 205, 210, 211, 212, 213, 215, 217, 219,
                221, 226, 241, 242, 249, 252, 254, 256 },
}

local TABLE_SQL = "CREATE TABLE IF NOT EXISTS `" .. Constant.DB_NAME .. "`.`paragon_solo_clears` ("
    .. "guid INT UNSIGNED NOT NULL, dungeon SMALLINT UNSIGNED NOT NULL, "
    .. "PRIMARY KEY (guid, dungeon)) ENGINE=InnoDB;"

-- LFG dungeon id (instance_encounters.lastEncounterDungeon) -> display
-- name. The full 5-man universe: 28 classic wings, 16+16 TBC, 16+16 WotLK.
local DUNGEONS = {
    -- Classic (wings count separately, matching the LFG tool)
    [1]   = "Wailing Caverns",
    [2]   = "Scholomance",
    [4]   = "Ragefire Chasm",
    [6]   = "The Deadmines",
    [8]   = "Shadowfang Keep",
    [10]  = "Blackfathom Deeps",
    [12]  = "The Stockade",
    [14]  = "Gnomeregan",
    [16]  = "Razorfen Kraul",
    [18]  = "Scarlet Monastery: Graveyard",
    [20]  = "Razorfen Downs",
    [22]  = "Uldaman",
    [24]  = "Zul'Farrak",
    [26]  = "Maraudon: Foulspore Cavern",
    [28]  = "The Temple of Atal'Hakkar",
    [30]  = "Blackrock Depths: Detention Block",
    [32]  = "Lower Blackrock Spire",
    [34]  = "Dire Maul: Warpwood Quarter",
    [36]  = "Dire Maul: Capital Gardens",
    [38]  = "Dire Maul: Gordok Commons",
    [40]  = "Stratholme: Crusaders' Square",
    [163] = "Scarlet Monastery: Armory",
    [164] = "Scarlet Monastery: Cathedral",
    [165] = "Scarlet Monastery: Library",
    [272] = "Maraudon: The Wicked Grotto",
    [273] = "Maraudon: Earth Song Falls",
    [274] = "Stratholme: The Gauntlet",
    [276] = "Blackrock Depths: Upper City",
    -- The Burning Crusade
    [136] = "Hellfire Ramparts",
    [137] = "The Blood Furnace",
    [138] = "The Shattered Halls",
    [140] = "The Slave Pens",
    [146] = "The Underbog",
    [147] = "The Steamvault",
    [148] = "Mana-Tombs",
    [149] = "Auchenai Crypts",
    [150] = "Sethekk Halls",
    [151] = "Shadow Labyrinth",
    [170] = "Old Hillsbrad Foothills",
    [171] = "The Black Morass",
    [172] = "The Mechanar",
    [173] = "The Botanica",
    [174] = "The Arcatraz",
    [198] = "Magisters' Terrace",
    [178] = "Auchenai Crypts (Heroic)",
    [179] = "Mana-Tombs (Heroic)",
    [180] = "Sethekk Halls (Heroic)",
    [181] = "Shadow Labyrinth (Heroic)",
    [182] = "The Black Morass (Heroic)",
    [183] = "Old Hillsbrad Foothills (Heroic)",
    [184] = "The Slave Pens (Heroic)",
    [185] = "The Steamvault (Heroic)",
    [186] = "The Underbog (Heroic)",
    [187] = "The Blood Furnace (Heroic)",
    [188] = "Hellfire Ramparts (Heroic)",
    [189] = "The Shattered Halls (Heroic)",
    [190] = "The Arcatraz (Heroic)",
    [191] = "The Botanica (Heroic)",
    [192] = "The Mechanar (Heroic)",
    [201] = "Magisters' Terrace (Heroic)",
    -- Wrath of the Lich King
    [202] = "Utgarde Keep",
    [203] = "Utgarde Pinnacle",
    [204] = "Azjol-Nerub",
    [206] = "The Oculus",
    [207] = "Halls of Lightning",
    [208] = "Halls of Stone",
    [209] = "The Culling of Stratholme",
    [214] = "Drak'Tharon Keep",
    [216] = "Gundrak",
    [218] = "Ahn'kahet: The Old Kingdom",
    [220] = "The Violet Hold",
    [225] = "The Nexus",
    [245] = "Trial of the Champion",
    [251] = "The Forge of Souls",
    [253] = "Pit of Saron",
    [255] = "Halls of Reflection",
    [205] = "Utgarde Pinnacle (Heroic)",
    [210] = "The Culling of Stratholme (Heroic)",
    [211] = "The Oculus (Heroic)",
    [212] = "Halls of Lightning (Heroic)",
    [213] = "Halls of Stone (Heroic)",
    [215] = "Drak'Tharon Keep (Heroic)",
    [217] = "Gundrak (Heroic)",
    [219] = "Ahn'kahet: The Old Kingdom (Heroic)",
    [221] = "The Violet Hold (Heroic)",
    [226] = "The Nexus (Heroic)",
    [241] = "Azjol-Nerub (Heroic)",
    [242] = "Utgarde Keep (Heroic)",
    [249] = "Trial of the Champion (Heroic)",
    [252] = "The Forge of Souls (Heroic)",
    [254] = "Pit of Saron (Heroic)",
    [256] = "Halls of Reflection (Heroic)",
}

CharDBExecute(TABLE_SQL)

local function IsBot(player)
    return player.IsPlayerBot and player:IsPlayerBot()
end

-- ============================================================================
-- CLEAR REGISTRY
-- ============================================================================

--- Session cache: { set = { [dungeonId] = true }, count = n }. Loaded
--- synchronously once per session on first use (load-once read, glyph
--- module pattern); writes go through async CharDBExecute.
local function Clears(player)
    local cached = player:GetData(CLEARS_KEY)
    if cached then
        return cached
    end
    local clears = { set = {}, count = 0 }
    local q = CharDBQuery("SELECT dungeon FROM `" .. Constant.DB_NAME
        .. "`.`paragon_solo_clears` WHERE guid = " .. player:GetGUIDLow())
    if q then
        repeat
            local dungeon = q:GetUInt32(0)
            -- ids no longer in the allowlist don't count (or display)
            if DUNGEONS[dungeon] then
                clears.set[dungeon] = true
                clears.count = clears.count + 1
            end
        until not q:NextRow()
    end
    player:SetData(CLEARS_KEY, clears)
    return clears
end

-- ============================================================================
-- APPLY
-- ============================================================================

local RESIL_MODS = { "CRIT_TAKEN_MELEE", "CRIT_TAKEN_RANGED", "CRIT_TAKEN_SPELL" }

local function ApplyResil(player, amount, apply)
    for _, key in ipairs(RESIL_MODS) do
        player:ApplyRatingMod(Constant.STATISTICS.COMBAT_RATING[key], amount, apply)
    end
end

local function ReconcileCrit(player, want)
    local have = player:GetData(CRIT_KEY) or 0
    local present = player:HasAura(CRIT_SPELL)
    if want == have and present == (want > 0) then
        return
    end
    if present then
        player:RemoveAura(CRIT_SPELL)
    end
    if want > 0 then
        player:CastCustomSpell(player, CRIT_SPELL, true, want)
    end
    player:SetData(CRIT_KEY, want)
end

--- Grants every achievement the registry says is owed. Idempotent
--- (HasAchieved guard in the core); the era metas and capstone also
--- complete natively via their type-8 criteria — these calls are the
--- retro-grant / self-heal path. The core REFUSES grants in GM mode
--- (with a chat error per call), so skip entirely and let the next
--- GM-off reconcile catch up.
local function ReconcileAchievements(player, clears)
    if player:IsGM() then
        return
    end
    local metas = 0
    for era, ids in pairs(ERA) do
        local all = true
        for _, id in ipairs(ids) do
            if clears.set[id] then
                player:SetAchievement(ACH_BASE + id)
            else
                all = false
            end
        end
        if all then
            player:SetAchievement(ACH_META[era])
            metas = metas + 1
        end
    end
    if metas == 3 then
        player:SetAchievement(ACH_CAPSTONE)
    end
end

-- ============================================================================
-- PUSH (track tooltip, delta-suppressed)
-- ============================================================================

local function Push(player, count, resil, crit, force)
    local sig = count .. ";" .. resil .. ";" .. crit
    if not force and player:GetData(PUSHED_KEY) == sig then
        return
    end
    player:SetData(PUSHED_KEY, sig)
    player:SendServerResponse(PREFIX, 1, {
        count = count,
        total = TOTAL,
        resil = resil,
        crit = crit,
        -- clears until the next whole crit percent (nil when maxed)
        next_at = count < TOTAL
            and (math.floor(count / CLEARS_PER_CRIT) + 1) * CLEARS_PER_CRIT
            or nil,
    })
end

-- ============================================================================
-- RECONCILE
-- ============================================================================

local function Reconcile(player, force)
    -- account-gate contract: bots and sub-80 alts compute nothing. The
    -- fast path still lets a de-leveled character with stale stats fall
    -- through to the strip below (gem-module symmetry).
    local eligible = not IsBot(player) and player:GetLevel() >= 80
    if not eligible
            and (player:GetData(APPLIED_KEY) or 0) == 0
            and not player:HasAura(CRIT_SPELL) then
        return -- fast path: nothing applied, nothing to strip (every bot)
    end
    local paragon = eligible and player:GetData("Paragon") or nil
    local owed = paragon and paragon:GetLevel() >= MILESTONE
    local clears = eligible and Clears(player) or nil
    local count = clears and clears.count or 0
    local resil = owed and count * RESIL_PER_CLEAR or 0
    local crit = owed and math.floor(count / CLEARS_PER_CRIT) or 0

    local prev = player:GetData(APPLIED_KEY) or 0
    if prev ~= resil then
        if prev > 0 then
            ApplyResil(player, prev, false)
        end
        if resil > 0 then
            ApplyResil(player, resil, true)
        end
        player:SetData(APPLIED_KEY, resil)
    end
    -- always: also clears a stale relog-restored aura (death-persistent)
    ReconcileCrit(player, crit)
    if clears then
        -- achievements follow the registry, not the milestone
        if count > 0 then
            ReconcileAchievements(player, clears)
        end
        Push(player, count, resil, crit, force)
    end
end

local function SafeReconcile(player, force, label)
    local ok, err = pcall(Reconcile, player, force)
    if not ok then
        print("[Paragon] solo dungeon " .. label .. " error: " .. tostring(err))
    end
end

-- ============================================================================
-- COMPLETION HOOK (§1p)
-- ============================================================================

local function OnEncounterComplete(event, map, creditType, creditEntry, source, dungeonId)
    if not dungeonId or dungeonId == 0 then
        return -- not the final encounter
    end
    local name = DUNGEONS[dungeonId]
    if not name then
        return -- raid, UBRS or holiday content
    end
    local players = map:GetPlayers()
    if not players or #players ~= 1 then
        return -- not solo (bots in the instance count as players)
    end
    local player = players[1]
    if IsBot(player) then
        return
    end
    local clears = Clears(player)
    if clears.set[dungeonId] then
        return -- already recorded (re-kills in the same instance included)
    end
    clears.set[dungeonId] = true
    clears.count = clears.count + 1
    CharDBExecute("INSERT IGNORE INTO `" .. Constant.DB_NAME
        .. "`.`paragon_solo_clears` (guid, dungeon) VALUES ("
        .. player:GetGUIDLow() .. ", " .. dungeonId .. ");")
    player:SendBroadcastMessage(string.format(
        "|cffffd100[Paragon]|r Solo clear recorded: %s (%d/%d)",
        name, clears.count, TOTAL))
    -- granted here rather than only via Reconcile so the achievement
    -- lands for any human, including below the level/paragon gates
    pcall(ReconcileAchievements, player, clears)
    SafeReconcile(player, false, "clear")
end

RegisterServerEvent(ENCOUNTER_EVENT, function(...)
    local ok, err = pcall(OnEncounterComplete, ...)
    if not ok then
        print("[Paragon] solo dungeon encounter error: " .. tostring(err))
    end
end)

-- ============================================================================
-- LIFECYCLE
-- ============================================================================

RegisterMediatorEvent("OnAfterClientLoadRequest", function(player, paragon)
    if player then
        SafeReconcile(player, true, "load")
    end
end)

RegisterMediatorEvent("OnParagonLevelChanged", function(player, paragon)
    if player then
        SafeReconcile(player, false, "level")
    end
end)

-- ReloadALE wipes the session store (APPLIED_KEY) while the rating mods
-- persist on live Player objects — the next reconcile would then stack a
-- second copy. Unapply before the state closes (event 16 fires before
-- lua_close, GetData still readable); the crit aura needs nothing, since
-- ReconcileCrit self-heals via HasAura.
RegisterServerEvent(16, function()
    local players = GetPlayersInWorld()
    if not players then
        return
    end
    for _, player in pairs(players) do
        local prev = player:GetData(APPLIED_KEY) or 0
        if prev > 0 then
            pcall(ApplyResil, player, prev, false)
        end
    end
end)

print("[Paragon] Rework: solo dungeon module loaded")
