#!/usr/bin/env python3
"""Generate paragon_companion_data.lua: the set of all companion spell ids.

Source: client SkillLineAbility.dbc rows with SkillLine == SKILL_COMPANIONS
(778) — the exact classification mod-collections uses (GetCollectionSpellType),
so the count always matches what the collection module syncs account-wide.
Names resolved from Spell.dbc for the comments. Used by
paragon_collection_xp.lua (milestone 325).
"""
import argparse
import os
import sys

import gen_glyph_data as g

OUT = os.path.join(g.REPO_ROOT, "serverside", "paragon", "modules",
                   "paragon_companion_data.lua")
SKILL_COMPANIONS = 778
# SkillLineAbility.dbc: ID(0), skillLine(1), spell(2), ...
SLA_SKILL_COL = 1
SLA_SPELL_COL = 2


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="fail instead of rewriting a stale artifact")
    parser.add_argument("--output", default=OUT,
                        help="generated Lua path (default: %(default)s)")
    args = parser.parse_args(argv)
    sla, _, _ = g.read_wdbc_ints(g.extract_dbc("SkillLineAbility.dbc"))
    companion_spells = sorted({rec[SLA_SPELL_COL] for rec in sla
                               if rec[SLA_SKILL_COL] == SKILL_COMPANIONS})
    if not companion_spells:
        sys.exit("no companion spells found — column mapping broken?")

    cols = g.spell_column_indices()
    name_col = cols["Name_Lang_enUS"]
    spells, _, block = g.read_wdbc_ints(g.extract_dbc("Spell.dbc"))
    names = {}
    for rec in spells:
        try:
            names[rec[0]] = g.string_at(block, rec[name_col])
        except Exception:
            pass

    lines = ["-- GENERATED by Tools/gen_companion_data.py - do not hand-edit.",
             "-- All SkillLineAbility.dbc spells in skill line 778 (Companions):",
             "-- %d spells — the same classification mod-collections syncs"
             % len(companion_spells),
             "-- account-wide, so HasSpell over this set counts the account",
             "-- collection.",
             "ParagonCompanionSpells = {"]
    for spell_id in companion_spells:
        lines.append("    [%d] = true, -- %s"
                     % (spell_id, names.get(spell_id, "?").replace("\n", " ")))
    lines.append("}")

    g.write_generated(args.output, "\n".join(lines) + "\n", args.check)
    verb = "verified" if args.check else "wrote"
    print(f"OK: {verb} {len(companion_spells)} companion spells -> {os.path.normpath(args.output)}")


if __name__ == "__main__":
    main()
