#!/usr/bin/env python3
"""Generate paragon_mount_data.lua: the set of all mount spell ids.

Source: client Spell.dbc — any spell with an effect applying
SPELL_AURA_MOUNTED (78). Players can only ever KNOW the learnable ones, so
checking HasSpell against the full set counts collected mounts without any
NPC-mount filtering. Used by paragon_mount_xp.lua (milestone 300).
"""
import os
import sys

import gen_glyph_data as g

OUT = os.path.join(g.HERE, "..", "Server", "azerothcore-test", "azerothcore-wotlk",
                   "env", "dist", "etc", "lua_scripts", "paragon", "modules",
                   "paragon_mount_data.lua")
SPELL_AURA_MOUNTED = 78


def main():
    cols = g.spell_column_indices()
    aura_idx = [cols["EffectAura_%d" % i] for i in (1, 2, 3)]
    name_col = cols["Name_Lang_enUS"]

    records, field_count, block = g.read_wdbc_ints(g.extract_dbc("Spell.dbc"))
    mounts = []
    for rec in records:
        if any(rec[a] == SPELL_AURA_MOUNTED for a in aura_idx):
            try:
                name = g.string_at(block, rec[name_col])
            except Exception:
                name = "?"
            mounts.append((rec[0], name))

    if not mounts:
        sys.exit("no mount spells found — column mapping broken?")

    lines = ["-- GENERATED by Tools/gen_mount_data.py - do not hand-edit.",
             "-- All Spell.dbc spells applying SPELL_AURA_MOUNTED (78): %d spells."
             % len(mounts),
             "-- Players only ever know the learnable ones, so HasSpell over this",
             "-- set counts collected mounts.",
             "ParagonMountSpells = {"]
    for spell_id, name in sorted(mounts):
        lines.append("    [%d] = true, -- %s" % (spell_id, name.replace("\n", " ")))
    lines.append("}")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"OK: {len(mounts)} mount spells -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
