#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Emit the Lua block that gives the nine non-Paladin classes their milestone
rewards, for paragon_rework_track.lua.

Three kinds of milestone come out of this, matching how the Paladin track is
already built:

  TALENT_MASTERY   informational label + the client-side talent-pane
                   coordinates the mask addon needs; the real gate is the
                   EXTENDED_TALENTS entry (also emitted here)
  TRAINER_RANKS_*  informational label; the real gate is the marker spell the
                   milestone teaches, which is class-agnostic and already
                   exists, so nothing new is needed server-side
  NO_REWARD        the placeholder for milestones whose Paladin reward is a
                   bespoke mechanic (a custom spell, a core patch, a brand-new
                   talent). Deliberately grants nothing: ApplyReward only acts
                   on UNIT_MODS and COMBAT_RATING, so an unknown SPECIAL value
                   is inert by construction, and the client renders the label
                   verbatim.

Run: python gen_class_track_lua.py > generated/class_track.lua
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "generated"))

from class_talent_ranks import CLASS_TALENT_RANKS, CLASS_TALENT_TRACK  # noqa
from class_trainer_ranks import CLASS_SPELL_RANKS                      # noqa

CLASS_ID = {"Warrior": 1, "Hunter": 3, "Rogue": 4, "Priest": 5,
            "Death Knight": 6, "Shaman": 7, "Mage": 8, "Warlock": 9,
            "Druid": 11}

# Milestones whose Paladin reward is a bespoke mechanic. Everyone else gets the
# note. Milestone 375 is NOT here: it went universal on 2026-08-20 because
# every class has an average item level.
NO_REWARD_LEVELS = [125, 225, 325, 425, 575, 675, 1075, 1325]
NO_REWARD_LABEL = "If you want this to have a cool effect, hmu <3 - Tom"

TRAINER_VALUE = {175: "TRAINER_RANKS", 525: "TRAINER_RANKS_525",
                 775: "TRAINER_RANKS_775", 900: "TRAINER_RANKS_900",
                 1175: "TRAINER_RANKS_1175", 1425: "TRAINER_RANKS_1425"}
WORD = {1: "one", 2: "two", 3: "three", 4: "four", 5: "five", 6: "six"}


def lua_icon(path):
    """SpellIcon.dbc stores backslashes; every icon already in the track uses
    forward slashes, and the 3.3.5 client accepts either."""
    return path.replace("\\", "/")


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    # talent_id -> number of new ranks
    adds = {e["talent_id"]: len(e["new_ranks"]) for e in CLASS_TALENT_RANKS}
    # (class, milestone) -> [ (talent_id, tab, tier, col, base, name, icon) ]
    talents = {}
    for cls, milestone, tid, tab, tier, col, base, name, icon in CLASS_TALENT_TRACK:
        talents.setdefault((cls, milestone), []).append(
            (tid, tab, tier, col, base, name, icon))

    # (class, milestone) -> [spell names], in wave order
    waves = {}
    for e in CLASS_SPELL_RANKS:
        waves.setdefault((e["cls"], e["milestone"]), []).append(e)

    out = []
    w = out.append
    w("-- " + "=" * 74)
    w("-- NON-PALADIN CLASS REWARDS")
    w("-- " + "=" * 74)
    w("--")
    w("-- GENERATED by Tools/gen_class_track_lua.py from the same data that")
    w("-- produced the spell rows -- do not hand-edit, regenerate. Every entry")
    w("-- mirrors the Paladin milestone it sits beside: where a Paladin")
    w("-- milestone raises one talent by four ranks, so does every other")
    w("-- class's; where it touches three talents, so do theirs.")
    w("--")
    w("-- The ONE deliberate break is the Death Knight's trainer waves: four")
    w("-- spells per wave instead of five or six. It has eight trainer-taught")
    w("-- rank chains where every other class has fourteen or more, because")
    w("-- its spells all start at level 55, and holding it to the same count")
    w("-- would drive single chains five ranks deep.")
    w("--")
    w("-- Milestones with no entry here are the ones whose Paladin reward is a")
    w("-- bespoke mechanic; they get NO_REWARD below.")
    w("")
    w("local CLASS_REWARDS = {}")
    w("")
    w("local function ClassReward(level, class_id, entry)")
    w("    CLASS_REWARDS[level] = CLASS_REWARDS[level] or {}")
    w("    CLASS_REWARDS[level][class_id] = entry")
    w("end")
    w("")

    levels = sorted(set(m for _, m in talents) | set(m for _, m in waves))
    for level in levels:
        w("-- ---- milestone %d %s" % (level, "-" * (60 - len(str(level)))))
        for cls in sorted(CLASS_ID, key=lambda c: CLASS_ID[c]):
            cid = CLASS_ID[cls]
            if (cls, level) in talents:
                picks = talents[(cls, level)]
                title = picks[0][5] if len(picks) == 1 else None
                icon = lua_icon(picks[0][6])
                w("ClassReward(%d, %d, {" % (level, cid))
                if title:
                    w('    title = "%s",' % esc(title))
                w('    icon = "%s",' % esc(icon))
                w("    rewards = {")
                for tid, tab, tier, col, base, name, _ in picks:
                    w("        { type = \"SPECIAL\", value = \"TALENT_MASTERY\", amount = %d," % adds[tid])
                    w('          label = "Maximum rank of the %s talent increased by %d",'
                      % (esc(name), adds[tid]))
                    w("          talent = { tab = %d, tier = %d, column = %d, base = %d } },"
                      % (tab, tier, col, base))
                w("    },")
                w("})   -- %s" % cls)
            elif (cls, level) in waves:
                wave = waves[(cls, level)]
                n = len(wave)
                more = "" if level == 175 else " more"
                w("ClassReward(%d, %d, {" % (level, cid))
                w("    rewards = { { type = \"SPECIAL\", value = \"%s\", amount = %d,"
                  % (TRAINER_VALUE[level], n))
                w('                  label = "New ranks for %s%s spells can be learned at your class trainer" } },'
                  % (WORD[n], more))
                w("})   -- %s: %s" % (cls, ", ".join(
                    "%s R%d" % (e["name"], e["rank"]) for e in wave)))
        w("")

    # ---- the placeholder ---------------------------------------------------
    w("-- ---- milestones with no class reward yet " + "-" * 33)
    w("--")
    w("-- The Paladin reward at each of these is a bespoke mechanic -- a custom")
    w("-- spell, a core patch, a brand-new talent -- not something that")
    w("-- generalises by picking a different talent or spell rank. Rather than")
    w("-- hand every other class a consolation stat, the milestone says so.")
    w("--")
    w("-- Grants nothing on purpose: ApplyReward only acts on UNIT_MODS and")
    w("-- COMBAT_RATING, the talent reconciler only matches TALENT_POINTS, and")
    w("-- every other SPECIAL handler matches its own value -- so an unknown")
    w("-- value is inert everywhere without needing a special case anywhere.")
    w("--")
    w("-- Plain ASCII <3 rather than a heart: the 3.3.5 UI font (FRIZQT__.TTF")
    w("-- in locale-enUS.MPQ) has no glyph for U+2764, and none for the plain")
    w("-- card-suit U+2665 either -- both would draw as an empty box.")
    w("local NO_REWARD_LEVELS = { %s }"
      % ", ".join(str(x) for x in NO_REWARD_LEVELS))
    w("")
    w("for _, level in ipairs(NO_REWARD_LEVELS) do")
    w("    for _, class_id in ipairs({ 1, 3, 4, 5, 6, 7, 8, 9, 11 }) do")
    w("        ClassReward(level, class_id, {")
    w("            rewards = { { type = \"SPECIAL\", value = \"NO_REWARD\", amount = 0,")
    w('                          label = "%s" } },' % esc(NO_REWARD_LABEL))
    w("        })")
    w("    end")
    w("end")
    w("")

    # ---- splice into the milestone tables -----------------------------------
    w("-- Fold the generated entries into the milestone tables declared above.")
    w("-- Kept as a data table plus one loop rather than 153 assignments so the")
    w("-- shape stays visible and a regenerated block is a clean diff.")
    tables = sorted(set(levels) | set(NO_REWARD_LEVELS))
    w("local MILESTONE_TABLES = {")
    for lv in tables:
        w("    [%d] = MILESTONE_%d," % (lv, lv))
    w("}")
    w("")
    w("for level, per_class in pairs(CLASS_REWARDS) do")
    w("    local tbl = MILESTONE_TABLES[level]")
    w("    if not tbl then")
    w("        print(string.format(")
    w('            "[Paragon] !! class rewards generated for milestone %d, which has no "')
    w('            .. "MILESTONE_%d table -- those rewards are silently lost", level, level))')
    w("    else")
    w("        for class_id, entry in pairs(per_class) do")
    w("            tbl[class_id] = entry")
    w("        end")
    w("    end")
    w("end")
    w("")

    # ---- EXTENDED_TALENTS gate rows ----------------------------------------
    w("-- Gate rows for EXTENDED_TALENTS (paste into that table): the reward")
    w("-- entries above are labels, THIS is what refuses the extra ranks until")
    w("-- the milestone lands. base = the talent's retail rank cap, which is")
    w("-- where the extended ranks start (0-based) -- it is NOT always 5.")
    for cls, milestone, tid, tab, tier, col, base, name, icon in CLASS_TALENT_TRACK:
        w("    [%d] = { milestone = %d, base = %d },  -- %s (%s)"
          % (tid, milestone, base, name, cls))

    print("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
