#!/usr/bin/env python3
"""Generate Paragon_EnchantText.lua: enchant id -> tooltip display text.

Source: client SpellItemEnchantment.dbc (enUS name column, autodetected by
matching known enchants: 3790 "Black Magic", 1103 "+26 Agility"). Used by
Paragon_DualEnchant.lua to render the second permanent weapon enchant
(prismatic slot, core patch §1e) that the client applies but never displays.

History: this generator once also emitted enchant-NAME sets for a
replace-popup auto-accept. That addon path is deleted (ReplaceEnchant() is
protected — the §1e eager-shift core addendum suppresses the popup
server-side instead), so only the id -> text table remains.
"""
import os
import sys

import gen_glyph_data as g

OUT = os.path.join(g.HERE, "..", "Client", "Interface", "AddOns", "Paragon",
                   "Paragon", "Paragon_EnchantText.lua")
KNOWN = {3790: "Black Magic", 1103: "+26 Agility"}


def main():
    records, field_count, block = g.read_wdbc_ints(
        g.extract_dbc("SpellItemEnchantment.dbc"))
    by_id = {r[0]: r for r in records}
    for want in KNOWN:
        if want not in by_id:
            sys.exit(f"enchant {want} not in DBC")

    name_col = None
    for col in range(1, field_count):
        try:
            if all(g.string_at(block, by_id[i][col]) == text
                   for i, text in KNOWN.items()):
                name_col = col
                break
        except Exception:
            continue
    if name_col is None:
        sys.exit("could not locate the enUS name column")

    def name_of(rec):
        try:
            return g.string_at(block, rec[name_col])
        except Exception:
            return ""


    def lua_str(text):
        return text.replace("\\", "\\\\").replace('"', '\\"')

    lines = ["-- GENERATED by Tools/gen_enchant_text.py - do not hand-edit.",
             "-- SpellItemEnchantment.dbc id -> enUS display text (name col %d)." % name_col,
             "ParagonEnchantText = {"]
    count = 0
    for r in sorted(records, key=lambda r: r[0]):
        text = name_of(r)
        if not text:
            continue
        lines.append('    [%d] = "%s",' % (r[0], lua_str(text)))
        count += 1
    lines.append("}")

    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"OK: {count} enchants (name col {name_col}) -> {os.path.normpath(OUT)}")


if __name__ == "__main__":
    main()
